SELECT MEMBER_NO, MEMBER_EMAIL, MEMBER_NM ,MEMBER_TEL,
       		MEMBER_ADDR, PROFILE_IMG, 
    		TO_CHAR( ENROLL_DT, 'YYYY-MM-DD HH24:MI:SS') AS ENROLL_DT, MEMBER_PW, MEMBER_TYPE
FROM MEMBER
WHERE MEMBER_EMAIL = 'user01@kh.or.kr'
AND SECESSION_FL = 'N' ;



-- 카카오 로그인 회원 정보 조회
SELECT * FROM MEMBER
WHERE MEMBER_EMAIL = 'kjy_1615@naver.com'
AND SECESSION_FL = 'N';


-- 카카오 로그인 시 비밀번호가 null 인가 조회 ANIMAL_DETAIL
SELECT * FROM MEMBER
WHERE MEMBER_EMAIL = 'kakao@user.com';


-- 카카오 로그인 시 처음 로그인한 회원의 정보 삽입TEST
INSERT INTO MEMBER 
VALUES(SEQ_MEMBER_NO.NEXTVAL,'kakao3@user.com',NULL,'kakaoname',null,
		DEFAULT,DEFAULT,DEFAULT,DEFAULT,DEFAULT);

-- 멤버 타입 변경 
UPDATE MEMBER SET
MEMBER_TYPE = 'K'
WHERE MEMBER_NO ='46';


-- MEMBER_TEL - NOT NULL 제약조건 빼기
ALTER TABLE "MEMBER"
MODIFY "MEMBER_TEL" NULL;

-- MEMBER_PW - NOT NULL 제약조건 빼기
ALTER TABLE "MEMBER"
MODIFY "MEMBER_PW" NULL;

-- 카카오 로그인 멤버 타입 - 플래그 K 넣기
-- 제약조건 조회
SELECT * FROM ALL_CONSTRAINTS WHERE TABLE_NAME = 'MEMBER';

-- memberType 체크 제약조건 (SYS_C0021379) 삭제 후 재생성
ALTER TABLE "MEMBER" DROP CONSTRAINT SYS_C0021379; 

ALTER TABLE "MEMBER" ADD CHECK("MEMBER_TYPE" IN ('M','A','K'));


-- 비밀번호 조회
SELECT MEMBER_PW FROM MEMBER
WHERE MEMBER_NO = 7;

-- 회원탈퇴
UPDATE MEMBER SET
SECESSION_FL = 'Y'
WHERE MEMBER_NO = 7;

UPDATE MEMBER SET
SECESSION_FL = 'N'
WHERE MEMBER_NO = 7;